apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Wazuh-OpenSearch

datasources:
  # ── Prometheus ────────────────────────────────────────────
  - name: Prometheus
    uid: prometheus_ds
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  # ── Loki (logs) ───────────────────────────────────────────
  - name: Loki
    uid: loki_ds
    type: loki
    access: proxy
    url: http://localhost:3100
    editable: true

  - name: Wazuh-OpenSearch
    uid: wazuh_ds
    type: grafana-opensearch-datasource
    access: proxy
    url: https://${WAZUH_PRIVATE_IP}:9200
    basicAuth: true
    basicAuthUser: ${WAZUH_INDEXER_USER}
    editable: true
    jsonData:
      database: "wazuh-alerts-*"
      timeField: "@timestamp"
      version: "2.0.0"
      flavor: "opensearch"
      logMessageField: "full_log"
      logLevelField: "rule.level"
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: ${WAZUH_INDEXER_PASSWORD}
