{
 "title": "SENTINEL - Resumen Ejecutivo",
 "tags": [
  "SENTINEL",
  "TFG"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "ESTADO GENERAL DE SERVIDORES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Web Server",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"Tienda-Web-Server\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU DB Server",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"Tienda-DB-Server\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  { "title": "MÉTRICAS WEB (APACHE)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Apache Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=\"Tienda-Web-Server\"}[5m])",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "MÉTRICAS BASE DE DATOS (MARIADB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Conexiones MariaDB Activas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=\"Tienda-DB-Server\"}"
    }
   ]
  },
  {
   "title": "Tráfico de Consultas SQL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions{instance=\"Tienda-DB-Server\"}[5m])",
     "legendFormat": "Queries/sec"
    }
   ]
  },
  { "title": "SEGURIDAD (WAZUH ALERTS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Registro de Seguridad Activo (SENTINEL)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "Alertas",
     "metrics": [
      { "id": "1", "type": "raw_data", "settings": { "size": "100" } }
     ],
     "query": "rule.level:>=3",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}