apiVersion: v1alpha1
sts-region: us-east-1

static:
  - name: rds_metrics
    namespace: AWS/RDS
    regions:
      - us-east-1
    dimensions:
      - name: DBInstanceIdentifier
        value: database-sentinel
    metrics:
      - name: CPUUtilization
        statistics: [Average]
        period: 60
        length: 600
      - name: DatabaseConnections
        statistics: [Average]
        period: 60
        length: 600
      - name: FreeStorageSpace
        statistics: [Average]
        period: 60
        length: 600

  - name: alb_metrics
    namespace: AWS/ApplicationELB
    regions:
      - us-east-1
    dimensions:
      - name: LoadBalancer
        value: app/Sentinel-ALB/b5f600e0080669d3
    metrics:
      - name: RequestCount
        statistics: [Sum]
        period: 60
        length: 600
      - name: TargetResponseTime
        statistics: [Average]
        period: 60
        length: 600
